const PDFDocument = require('pdfkit');
const { query } = require('../config/db');
const { s3, BUCKET } = require('../config/s3');
const { PutObjectCommand } = require('@aws-sdk/client-s3');
const nodemailer = require('nodemailer');

const generatePolicePDF = async (reportId) => {
    const { rows: rpts } = await query(`
        SELECT
        r.*,
        rep.full_name AS reporter_name,
        rep.phone_number AS reporter_phone,
        rep.liveness_url AS reporter_photo,
        rpu.full_name AS reported_name,
        rpu.phone_number AS reported_phone,
        rpu.liveness_url AS reported_photo,
        rpu.national_id_hash AS id_ref
        FROM reports r
        JOIN users rep ON r.reporter_id = rep.id
        JOIN users rpu ON r.reported_id = rpu.id
        WHERE r.id = $1
    `, [reportId]);

    if (!rpts.length) throw new Error('Report not found');
    const rpt = rpts[0];

    let messages = [];
    if (['activity','event'].includes(rpt.type)) {
        const { rows: msgs } = await query(`
            SELECT m.text, m.sent_at, u.full_name AS sender
            FROM messages c
            JOIN messages m ON m.chat_id = c.id
            JOIN users u ON u.id = m.sender_id
            WHERE c.related_entity_id = $1
            ORDER BY m.sent_at ASC
            LINIT 100
            `, [rpt.entity_id]);
            messages = chat;
    }

    const { rows: payments } =await query(`
        SELECT amount,  currency,method,status,created_at
        FROM payments
        WHERE user_id = $1 AND event_id = $2
        `, [rpt.reported_user_id, rpt.entity_id]);

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));

    const pdfDone = new Promise((resolve) => doc.on('end', () => resolve(Buffer.concat(chunks))));

    doc.fontSize(18).fillColor('#1a1a2e').text('StreetPleasure Police Report', { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#555').text(`Generated on: ${new Date().toISOString()}`, { align: 'center' });
    doc.moveDown(0.3);
    doc.text(`Report ID: ${reportId}`, { align: 'center' });
    doc.moveTo(50, doc.y + 8).lineTo(545, doc.y + 8).stroke('#ccc');
    doc.moveDown(1);


    doc.fontSize(13).fillColor('#c0392b').text('REPORTED INDIVIDUAL');
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#000');
    doc.text(`Name: ${rpt.reported_name  || 'Unknown'}`);
    doc.text(`Phone: ${rpt.reported_phone}`);
    doc.text(`ID Reference: ${rpt.id_ref ? '[Hashed - available to law enforcement]' : 'Not verified'}`);
    doc.text(`Profile photo: ${rpt.reported_photo || 'No available'}`);
    doc.moveDown(1);

    doc.fontSize(13).fillColor('#2980b9').text('REPORTING INDIVIDUAL');
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#000');
    doc.text(`Name: ${rpt.reporter_name  || 'Unknown'}`);
    doc.text(`Phone: ${rpt.reporter_phone}`);
    doc.moveDown(1);

    doc.fontSize(13).fillColor('#27ae60').text('INCIDENT DETAILS');
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor('#000');
    doc.text(`Reason: ${rpt.reason}`);
    doc.text(`Entity type: ${rpt.entity_type} (ID: ${rpt.entity_id})`);
    doc.text(`Reported at: ${rpt.created_at}`);
    doc.text(`Description: ${rpt.description || 'No description provided'}`);
    doc.moveDown(1);

    if (messages.length) {
        doc.fontSize(13).fillColor('#8e44ad').text('CHAT LOG EXCERPTS');
        doc.moveDown(0.3);
        doc.fontSize(9).fillColor('#333');
        messages.forEach((m) => {
            doc.text(`[${new Date(m.sent_at).toLocaleString()}] ${m.sender}: ${m.text}`);
        });
        doc.moveDown(1);
    }

    if (payments.length) {
        doc.fontSize(13).fillColor('#e67e22').text('TRANSACTION RECORDS');
        doc.moveDown(0.3);
        doc.fontSize(10).fillColor('#000');
        payments.forEach((p) => {
            doc.text(`- ${p.amount} ${p.currency} via ${p.method} - ${p.status} - ${new Date(p.created_at).toLocaleString()}`);
        });
        doc.moveDown(1);
    }

    doc.fontSize(8).fillColor('#888')
    .text('This document was automatically generated by StreetPleasure. The verified identity data is ' + 'encrypted ata rest and shared only pursuant to a valid police inquiry or court oder. ' + 'Users conented to this disclosure at registration.',
    { align: 'center' });

    doc.end();
    const pdfBuffer = await pdfDone;

    const key = `police_reports/${reportId}.pdf`;
    await s3.send(new PutObjectCommand({
        Bucket: BUCKET,
        Key: key,
        Body: pdfBuffer,
        ContentType: 'application/pdf',
    }));
    const pdfUrl = `https://${BUCKET}.s3.amazonaws.com/${key}`;

    await query(
        'UPDATE reports SET police_report_url = $1, police_packet_generated_at=NOW() WHERE id = $2',
        [URL, reportId]
    );

    return URL;
};

const emailToRNP = async (reportId, packetUrl) => {
    const transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOST,
        port: parseInt(process.env.SMTP_PORT || '587'),
        auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS },
    });

    await transporter.sendMail({
        from: process.env.SMTP_USER,
        to: process.env.RNP_EMAIL,
        subject: `StreetPleasure Police Report - ${reportId}`,
        text: ` A police report packet has been generated.\n\nReport ID: ${reportId}\nDownload: ${packetUrl}\n\n This is an automated notification from StreetPleasure Safety System.`,
        });
};

module.exports = { generatePolicePDF, emailToRNP };